--!strict
local PLIP = "rbxassetid://129082045299062"
local PLOP = "rbxassetid://82560925076544"
local BAT_SWING = "rbxassetid://9113305311"

return {
    IngredientPickupSoundId = PLIP,
    IngredientPlantSoundId = PLIP,
    IngredientThrowSoundId = PLOP,
    BatSwingSoundId = BAT_SWING,
    CustomerHurtSoundId = "rbxassetid://126967734395019",
    SoundVolume = 0.7,
    SoundRollOffMinDistance = 10,
    SoundRollOffMaxDistance = 50,
}
